apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - image: httpd:2.4
          name: apache
          ports:
            - containerPort: 80
volumeMounts:
        - name: hello-config-vol
          mountPath: /opt/hello.txt
          subPath: hello.txt
volumes:
      - name: hello-config-vol
        configMap:
          name: hello-config